# Stage 1: Build
FROM golang:1.22-alpine AS builder

WORKDIR /app

# Install git and needed packages for go modules
RUN apk add --no-cache git

# Copy go mod and sum first
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the app
COPY . .

# Build the Go app
RUN go build -o chitchat-app ./cmd/server

# Stage 2: Runtime
FROM alpine:latest

WORKDIR /app

# Copy binary from builder
COPY --from=builder /app/chitchat-app .

# Copy migrations
COPY --from=builder /app/migrations ./migrations

# Expose port
EXPOSE 4000

# Run the binary
CMD ["./chitchat-app"]
